#!/usr/bin/env bash

exec > >(tee -a ${HOME}/hypy_install.log) 2>&1

# Prompt to gather data
function prompt {
    local message=$1
    local variable=$2
    local default=$3
    tput setaf 15
    read -p "${message} (default: ${default}): " value
    tput sgr0
    eval $variable=${value:-$default}
}

# Cool logo message
function logo() {
    local text=$1
    local red=$(tput setaf 1; tput bold)
    local green=$(tput setaf 2; tput bold)
    local blue=$(tput setaf 4; tput bold)
    local yellow=$(tput setaf 3; tput bold)
    local reset=$(tput sgr0)
    local screen_width=$(tput cols)
    local logo_text="${red}H${green}y${blue}p${yellow}y${reset}"
    local logo_width=4
    clear
    printf "\n\n"
    printf "%*s%s\n" $(( (screen_width - logo_width) / 2 )) "" "$logo_text"
    printf "\n%*s%s%s%s\n\n" $(( (screen_width - ${#text}) / 2 )) "" "$blue" "$text" "$reset"
}

logo "Press any key to continue..."
read

# Information gathering
prompt "Shell" SHELL /bin/zsh
prompt "Keymap" KEYMAP us
prompt "Console font" CONSOLE_FONT ter-132b
prompt "IRSSI username" IRSSI_USERNAME "None"
prompt "IRSSI password" IRSSI_PASSWORD "None"
prompt "Github token (optional)" TOKEN "None"

select AUR_HELPER in "Paru" "Yay"; do
    case $AUR_HELPER in
        "") AUR_HELPER="paru-bin"; break;;
        "Paru") AUR_HELPER="paru-bin"; break;;
        "Yay") AUR_HELPER="yay-bin"; break;;
    esac
done

if [[ ! -f "packages" ]]; then
  logo "Error: packages file not found!"
  exit 1
fi

logo "Sync repos..."
sudo pacman -Syy

while read package
do
  if [[ $package == "" ]] || [[ $package == \#* ]]; then
    continue
  fi
  logo "Installing: $package..."
  sudo pacman -S --noconfirm --needed "$package" 2> /dev/null
done < packages

logo "Installing an AUR helper: ${AUR_HELPER}..."
git clone https://aur.archlinux.org/${AUR_HELPER}.git
cd ${AUR_HELPER}
makepkg -si --noconfirm
cd ..
rm -rf ${AUR_HELPER}

logo "Switch shell to '${SHELL}'..."
sudo chsh -s ${SHELL} root 1> /dev/null
sudo chsh -s ${SHELL} ${USER} 1> /dev/null

logo "Changing default console font..."
echo -ne "KEYMAP=\"$KEYMAP\"\nFONT=\"$CONSOLE_FONT\"\n" | sudo tee /etc/vconsole.conf 1> /dev/null

logo "Adding no password sudo rights..."
sudo sed -ni "/^root/{a\
  ${USER} ALL=(ALL:ALL) NOPASSWD: ALL
p}" /etc/sudoers

logo "Github configuration..."
if [ -n "$TOKEN" ]; then
  cd ${HOME} 1> /dev/null
  echo -ne "https://nemo256:${TOKEN}@github.com" > ${HOME}/.git-credentials
  git config --global credential.helper store 1> /dev/null
fi

logo "Font configuration..."
cd /usr/share/fonts 1> /dev/null
sudo curl -fLo "Fira Code Bold Nerd Font Complete.ttf" https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete.ttf 1> /dev/null
sudo fc-cache -fv 1> /dev/null
cd ${HOME} 1> /dev/null

logo "Cloning Hypy repo..."
git clone https://github.com/nemo256/Hypy.git ${HOME}/Hypy

# Assuming the repo has configuration files to be stowed
cd ${HOME}/Hypy
stow -t ${HOME} .

logo "Irssi configuration..."
cp -fvr ${HOME}/Hypy/config/irssi/.irssi ${HOME}
sed -i "s/sasl_username = \".*\"/sasl_username = \"$IRSSI_USERNAME\"/" "${HOME}/.irssi/config"
sed -i "s/sasl_password = \".*\"/sasl_password = \"$IRSSI_PASSWORD\"/" "${HOME}/.irssi/config"
sed -i "s/nick = \".*\"/nick = \"$IRSSI_USERNAME\"/" "${HOME}/.irssi/config"

logo "Make binary files executable..."
chmod -R 755 ${HOME}/bin 1> /dev/null

logo "Protonvpn configuration..."
${AUR_HELPER} -S --noconfirm protonvpn-cli
protonvpn-cli config --vpn-accelerator enable

logo "Managing Essential Services..."
sudo systemctl disable transmission.service
sudo systemctl enable bluetooth.service

logo "Setting up disable_prochot.service..."
sudo echo -ne "[Unit]\nDescription=Disable BD_PROCHOT to enable better performance without the battery\nAfter=network.target\n\n[Service]\nType=simple\nUser=root\nExecStart=wrmsr 0x1FC 2\n\n[Install]\nWantedBy=default.target" | sudo tee /etc/systemd/system/disable_prochot.service
sudo systemctl enable disable_prochot.service

logo "Done - Script finished installing and configuring n3m0's Hypy!"
